services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE:-Europe/Paris}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM:? [Plex] need a claim token}
    volumes:
      - ${CONTAINER_PATH:? need container path}/plex/library:/config
      - ${DATA_PATH:? need data path}/tvseries:/tv
      - ${DATA_PATH:? need data path}/movies:/movies
    depends_on:
      - transmission-openvpn
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE:-Europe/Paris}
    volumes:
      - ${CONTAINER_PATH:? need container path}/sonarr/data:/config
      - ${DATA_PATH:? need data path}/tvseries:/tv #optional
      - ${DATA_PATH:? need data path}/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
    depends_on:
      - prowlarr
      - transmission-openvpn

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE:-Europe/Paris}
    volumes:
      - ${CONTAINER_PATH:? need container path}/radarr/data:/config
      - ${DATA_PATH:? need data path}/movies:/movies #optional
      - ${DATA_PATH:? need data path}/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
    depends_on:
      - prowlarr
      - transmission-openvpn

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE:-Europe/Paris}
    volumes:
      - ${CONTAINER_PATH:? need container path}/bazarr/config:/config
      - ${DATA_PATH:? need data path}/movies:/movies #optional
      - ${DATA_PATH:? need data path}/tvseries:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped
    depends_on:
      - radarr
      - sonarr

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE:-Europe/Paris}
    volumes:
      - ${CONTAINER_PATH:? need container path}/prowlarr/data:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE:-Europe/Paris}
    volumes:
      - ${CONTAINER_PATH:? need container path}/overseerr/config:/config
    ports:
      - 5055:5055
    restart: unless-stopped
    depends_on:
      - plex

  transmission-openvpn:
    image: haugene/transmission-openvpn
    container_name: transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - ${CONTAINER_PATH:? need container path}/transmission/config/:/config
      - ${DATA_PATH:? need data path}/downloads/:/data
    environment:
      - OPENVPN_PROVIDER=${OPENVPN_PROVIDER:? [Deluge] need a provider}
      - OPENVPN_CONFIG=${OPENVPN_CONFIG:? [Deluge] need a config file}
      - OPENVPN_USERNAME=${OPENVPN_USERNAME:? [Deluge] need a username}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD:? [Deluge] need a password}
      - LOCAL_NETWORK=${OPENVPN_LOCAL_NETWORK:? [Deluge] need a local network}
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - 9091:9091
    restart: unless-stopped
